language: csharp
dotnet: 2.2
sudo: required
solution: VerifyWorldHolidays.sln
script:
 - dotnet restore
 - msbuild /p:Configuration=Release solution-name.sln
 - mono ./HoliDayDateTest/bin/netcoreapp2.2/HoliDayDateTest.dll
