env:
    - sonarQube

language: csharp
os: linux
mono: latest
sudo: required
dist: xenial
dotnet: 3.1

addons:
    apt:
        packages:
            - gettext
            - libcurl4-openssl-dev
            - libicu-dev
            - libssl-dev
            - libunwind8
            - zlib1g

before_install:
    #   - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch origin

install:
    - sudo apt-get install -qq dotnet-sdk-2.1.0

script:
    # You must run this command to give Travis permissions to execute the build.sh shell script:
    # git update-index --chmod=+x ./build.sh
    - bash ./build.sh
    # - dotnet restore
    # - dotnet build
    # - cd tests/Generic.Repository.Test
    # - dotnet test

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
