language: csharp
solution: VerifyWorldHolidays.sln
install:
  - nuget restore VerifyWorldHolidays.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release VerifyWorldHolidays.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./HoliDayDateTest/bin/netcoreapp2.2/HoliDayDateTest.dll