image:
  - Visual Studio 2019
version: "{build}"
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_KEY:
    secure: I7+DNEf68Q58NXUqUhhs6L46S1pUpjZ5lS1tx3FtyGk=
build_script:
  - ps: .\build.ps1
test: on
artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
