name: ASP.NET Core CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*.*.*"
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        core_version: [3.1]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - run: |
          dotnet --info
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
      - if: contains(matrix.os, 'windows')
        run: ./build.ps1
        shell: pwsh
      - if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
        run: ./build.sh
